name = "my-worker"
compatibility_date = "2026-08-14"
main = "server.js"

[[d1_databases]]
binding = "DB"
database_name = "meu-campus-db"
database_id = "d5301d77-3042-4685-8df2-2d6c44570c40"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "meu-campus-assets"

